### ISSUE TITLE
Orders short 1 table

### ISSUE THREAD

**Issue by Marco-Group** [sg-p4x347/Efficient-Automatic-Traveler-System#35]
These are the ones we spoke about yesterday, but am needing to send to you through this system.
These are missing or are short 1 table in shipping. 

5039434 -MG2228-50 (1)
5038133 - 38-2270-50 (1)
5039512 - 41-2422-78 (1)
5039507 - MG2237-82 (1)
5039667 - MG2250-49 (1)

These are the ones that you hand keyed yesterday. 

Shalee

**Comment by sg-p4x347** [comment]
Old travelers still in the system that were deleted:
92879
93566
95306
144146
95321
