### ISSUE TITLE
GHOST TABLES IN EATS

### ISSUE THREAD

**Issue by Marco-Group** [sg-p4x347/Efficient-Automatic-Traveler-System#46]
Ok, so we had another one where EASTS didn't tell us to build certain tables on an order.
Order 5039702 has 5 of the 38-2236-22 tables on it. 
On the 19th, we pulled all orders through the ship date of the 17th. 
5039702 is on that summary... but not for those 5 tables.
AND, that table is on the summary... but not for 5039702. It tells us to only build 5 for order 5039138. 

We need to find out why EATS didn't pick up those 5 tables for the order 5039702.

Thanks
Shalee

**Comment by sg-p4x347** [comment]
After going through the data, It is still uncertain to determine why that order was not included.
This has prompted me to make an "OnHand" audit field for the travelers at the time of creation
