### ISSUE TITLE
traveler 155805

### ISSUE THREAD

**Issue by Marco-Group** [sg-p4x347/Efficient-Automatic-Traveler-System#54]
I have already spoke with you on this, but here is the ticket so we can look into the issue further. 

Traveler 155805 shows 3 items completed and the 4th item as In Process...

The 4th item shows being completed multiple times at the trimmer, but at the pack line it is showing "Started" which doesn't make sense since we only do the one scan now which prints their label and then also completes the item. 
Please let me know what you find out on this perplexing issue.

Thanks
Shalee

**Comment by sg-p4x347** [comment]
The database reflects the same information for this item that is displayed, It was completed several times at the trimmer, and only started at Table-Pack2. I suspect that an exception was thrown after starting the item, which would have made it miss the completion phase. I've put in a handler so it should complete it regardless if the start fails.
